function C2FQbatchsummaryNASCENT2003032 = importTS_Summary(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   C2FQBATCHSUMMARYNASCENT2003032 = IMPORTFILE(FILENAME) Reads data from
%   text file FILENAME for the default selection.
%
%   C2FQBATCHSUMMARYNASCENT2003032 = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   C2FQbatchsummaryNASCENT2003032 = importfile('C2-FQ_batch_summary_NASCENT_200303_2.txt', 14, 53);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2020/03/05 15:22:54

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 14;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]);
rawStringColumns = string(raw(:, [1,22,23]));


%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
idx = (rawStringColumns(:, 1) == "<undefined>");
rawStringColumns(idx, 1) = "";

%% Create output variable
C2FQbatchsummaryNASCENT2003032 = table;
C2FQbatchsummaryNASCENT2003032.FILE = categorical(rawStringColumns(:, 1));
C2FQbatchsummaryNASCENT2003032.CELL = cell2mat(rawNumericColumns(:, 1));
C2FQbatchsummaryNASCENT2003032.TS = cell2mat(rawNumericColumns(:, 2));
C2FQbatchsummaryNASCENT2003032.N_IntInt = cell2mat(rawNumericColumns(:, 3));
C2FQbatchsummaryNASCENT2003032.N_PSFsup = cell2mat(rawNumericColumns(:, 4));
C2FQbatchsummaryNASCENT2003032.N_PSFsup_std = cell2mat(rawNumericColumns(:, 5));
C2FQbatchsummaryNASCENT2003032.N_SumPix = cell2mat(rawNumericColumns(:, 6));
C2FQbatchsummaryNASCENT2003032.N_Amp = cell2mat(rawNumericColumns(:, 7));
C2FQbatchsummaryNASCENT2003032.N_MaxInt = cell2mat(rawNumericColumns(:, 8));
C2FQbatchsummaryNASCENT2003032.sigma_xy = cell2mat(rawNumericColumns(:, 9));
C2FQbatchsummaryNASCENT2003032.sigma_z = cell2mat(rawNumericColumns(:, 10));
C2FQbatchsummaryNASCENT2003032.AMP = cell2mat(rawNumericColumns(:, 11));
C2FQbatchsummaryNASCENT2003032.BGD = cell2mat(rawNumericColumns(:, 12));
C2FQbatchsummaryNASCENT2003032.Size_meannm = cell2mat(rawNumericColumns(:, 13));
C2FQbatchsummaryNASCENT2003032.Size_stdnm = cell2mat(rawNumericColumns(:, 14));
C2FQbatchsummaryNASCENT2003032.BGD_cell = cell2mat(rawNumericColumns(:, 15));
C2FQbatchsummaryNASCENT2003032.TS_PixSum = cell2mat(rawNumericColumns(:, 16));
C2FQbatchsummaryNASCENT2003032.PSF_BgdSum = cell2mat(rawNumericColumns(:, 17));
C2FQbatchsummaryNASCENT2003032.TS_MaxInt = cell2mat(rawNumericColumns(:, 18));
C2FQbatchsummaryNASCENT2003032.x_pos = cell2mat(rawNumericColumns(:, 19));
C2FQbatchsummaryNASCENT2003032.y_pos = cell2mat(rawNumericColumns(:, 20));
C2FQbatchsummaryNASCENT2003032.mRNAx_pos = rawStringColumns(:, 2);
C2FQbatchsummaryNASCENT2003032.mRNAy_pos = rawStringColumns(:, 3);

